// <auto-generated />
using System;
using ApiP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiP.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20211220234852_Mig2")]
    partial class Mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiP.Data.CzasowoOdebrane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataOddania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOdebrania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWystawienia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKierowcy")
                        .HasColumnType("int");

                    b.Property<int?>("KierowcaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KierowcaID");

                    b.ToTable("CzasowoBd");
                });

            modelBuilder.Entity("ApiP.Data.Historia", b =>
                {
                    b.Property<int>("PESEL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PESEL");

                    b.ToTable("HistoriaBd");
                });

            modelBuilder.Entity("ApiP.Data.Kierowcy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CzyOdebrano")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data_orzymania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_ur")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Pkt")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("KierowcyBd");
                });

            modelBuilder.Entity("ApiP.Data.Mandaty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataOplacenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWydania")
                        .HasColumnType("datetime2");

                    b.Property<int>("KierowcyID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowodID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KierowcyID");

                    b.HasIndex("PowodID");

                    b.ToTable("MandatyBd");
                });

            modelBuilder.Entity("ApiP.Data.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazwa_Roli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RolesBd");
                });

            modelBuilder.Entity("ApiP.Data.Taryfikator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Liczba_PKT")
                        .HasColumnType("int");

                    b.Property<int>("MiesiąceWstrzymania")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TaryfikatorBd");
                });

            modelBuilder.Entity("ApiP.Data.Users", b =>
                {
                    b.Property<int>("Nr_Sluzbowy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_ur")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRoli")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nr_tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("RolaID")
                        .HasColumnType("int");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("Nr_Sluzbowy");

                    b.HasIndex("RolaID");

                    b.ToTable("UsersBd");
                });

            modelBuilder.Entity("ApiP.Data.CzasowoOdebrane", b =>
                {
                    b.HasOne("ApiP.Data.Kierowcy", "Kierowca")
                        .WithMany()
                        .HasForeignKey("KierowcaID");

                    b.Navigation("Kierowca");
                });

            modelBuilder.Entity("ApiP.Data.Mandaty", b =>
                {
                    b.HasOne("ApiP.Data.Kierowcy", "Kierowcy")
                        .WithMany("Mandaty")
                        .HasForeignKey("KierowcyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiP.Data.Taryfikator", "Powod")
                        .WithMany()
                        .HasForeignKey("PowodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierowcy");

                    b.Navigation("Powod");
                });

            modelBuilder.Entity("ApiP.Data.Users", b =>
                {
                    b.HasOne("ApiP.Data.Role", "Rola")
                        .WithMany()
                        .HasForeignKey("RolaID");

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("ApiP.Data.Kierowcy", b =>
                {
                    b.Navigation("Mandaty");
                });
#pragma warning restore 612, 618
        }
    }
}
